### ISSUE TITLE
Addition of QUIC protocol in security.tls.v1_2_client

### ISSUE THREAD

**Issue by travellingmonk** [google/testrun#452]
Addition of cryptographic primitives for QUIC protocol (security.tls.v1_2_server test). As of devices utilizing QUIC will generate a 'Non-Complaint' result for TLSv1.2 test.

Please see screenshot:

![image](https://github.com/google/testrun/assets/149505525/68151eaf-8961-4aa9-8563-dfeae0c8918f)

![image](https://github.com/google/testrun/assets/149505525/75dccc36-d215-4659-a6a2-d1058f880118)

**Comment by jhughesbiot** [comment]
This looks like tls client test failures, not server.  I'm not sure we can allow this traffic right now as it does not appear to be an approved form of outbound traffic based on the current security requirements which requires TLS as it's form of encryption.  https://partner-security.withgoogle.com/docs/iot_requirements#tls

Since this is an encrypted UDP protocol and we only have TCP encryption defined, we would need to get new definitions and allowances for this specific protocol that we are able to validate against.

**Comment by travellingmonk** [comment]
Thanks for the correction

**Comment by jboddey** [comment]
This will be released in v1.3 (end of June)
